nelmio_api_doc:
    documentation:
        info:
            title: BasicAPI
            description: Recruitment task
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
